language: ruby
rvm:
  - 2.4.0

services:
  - postgresql
  - redis-server

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system

before_script:
  - psql -c "CREATE USER \"freecodecamp-meetup-api\" WITH PASSWORD 'freecodecamp-meetup-api';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"freecodecamp-meetup-api_test\";" -U postgres
  - psql -c "CREATE DATABASE \"freecodecamp-meetup-api_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

notifications:
  email: false

cache:
  bundler: true
